markdown: rdiscount
permalink: /:title/
url: http://lizekui.github.io
name: zkli's blog
url_personalpage: http://ir.hit.edu.cn/~zkli/
name_personalpage: zkli's personal page
author: zkli
email: lzkhitcs@gmail.com
duoshuo: zkli
cnzz: 1000241417
weibo: 1954463527
beian: 黑ACE备22222222号
github: lizekui
pygments: true
safe: true
paginate: 20
about: "Remember Why You Started."